# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-23 20:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_coverphoto',
            new_name='article_photo',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='article_subtitle',
            new_name='article_summary',
        ),
    ]
