# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-09 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_photo',
        ),
        migrations.AlterField(
            model_name='article',
            name='article_photosrc',
            field=models.URLField(max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_url',
            field=models.URLField(max_length=100),
        ),
    ]
