# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-06 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20170823_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_author',
        ),
        migrations.AddField(
            model_name='article',
            name='article_photosrc',
            field=models.URLField(default=b'DEFAULT VALUE', max_length=300),
        ),
        migrations.AddField(
            model_name='article',
            name='article_site',
            field=models.CharField(default=b'', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_url',
            field=models.URLField(),
        ),
    ]
